[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "up_ac"
authors = [{name = "DW", email = "dimitri-weiss@web.de"}]
dynamic = ["version", "description"]
