

name: UPAC

on:
  push:
    branches: 
      - main
      - dev
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check-token:
    runs-on: ubuntu-latest
    steps:
      - name: Debug GitHub PAT
        run: |
          echo "Checking GITHUB_PAT..."
          if [ -z "$GITHUB_PAT" ]; then
            echo "❌ GITHUB_PAT is not set"
            exit 1
          else
            echo "✅ GITHUB_PAT is set"
            curl -H "Authorization: token $GITHUB_PAT" https://api.github.com/user
          fi
        env:
          GITHUB_PAT: ${{ secrets.WORKFLOW }}
  build:

    runs-on: ${{ matrix.os }}
    name: Test UPAC on ${{ matrix.os }} and Irace from ${{ matrix.r-package-source }}
    env: 
      GITHUB_PAT: ${{ secrets.WORKFLOW }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        python-version: ["3.8"]
        pip-args: ["--upgrade"]
        r-version: ["release"]
        r-package-source: ["github::MLopez-Ibanez/irace"]

    steps:

    - name: Check GitHub PAT
      env:
        GITHUB_PAT: ${{ secrets.WORKFLOW }}
        GH_TOKEN: ${{ secrets.WORKFLOW }}  # Needed for gh CLI if used
      run: |
        if [ -z "$GITHUB_PAT" ]; then
          echo "❌ GITHUB_PAT is not set"
          exit 1
        else
          echo "✅ GITHUB_PAT is set"
          gh auth status || echo "⚠️ Warning: Authentication check failed"
        fi
      

    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip

    - name: Set up R 
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ matrix.r-version }}
        use-public-rspm: true

    - uses: r-lib/actions/setup-r-dependencies@v2
      if: ${{ matrix.r-package-source == 'github::MLopez-Ibanez/irace' }}
      #with:
      #  packages: remotes
      #  pak-version: devel
      with:
        packages: ${{ matrix.r-package-source }}
        dependencies: '"hard"'
        pak-version: devel

    - name: Install github::MLopez-Ibanez/irace
      if: ${{ matrix.r-package-source == 'github::MLopez-Ibanez/irace' }}
      env:
        GITHUB_PAT: ${{ secrets.WORKFLOW }}  # Ensure the token is passed
      run: |
        Sys.setenv(GITHUB_PAT = Sys.getenv("GITHUB_PAT"))
        install.packages("remotes")
        remotes::install_github('MLopez-Ibanez/irace', upgrade = 'never', build = FALSE)
      shell: Rscript {0}

    - uses: r-lib/actions/setup-r-dependencies@v2
      if: ${{ matrix.r-package-source == 'cran::irace' }}
      with:
        packages: ${{ matrix.r-package-source }}
        dependencies: '"hard"'
        pak-version: devel

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test with unittest
      run: |
        python -m unittest up_ac/tests/unittests.py
        python -m unittest up_ac/tests/test_default_engine_configs.py
        python -m unittest up_ac/tests/test_allowed_combinations.py
        #python -m unittest up_ac/tests/test_enhsp_Irace.py
        #python -m unittest up_ac/tests/test_fast-downward_Smac.py
        python -m unittest up_ac/tests/test_lpg_OAT.py
